# Generated by Django 2.0.5 on 2018-10-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_pst_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pst_tag',
        ),
    ]
