# Generated by Django 2.0.5 on 2018-10-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_pst_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
